require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AccountSubtypesController do

  # This should return the minimal set of attributes required to create a valid
  # AccountSubtype. As you add validations to AccountSubtype, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all account_subtypes as @account_subtypes" do
      account_subtype = AccountSubtype.create! valid_attributes
      get :index
      assigns(:account_subtypes).should eq([account_subtype])
    end
  end

  describe "GET show" do
    it "assigns the requested account_subtype as @account_subtype" do
      account_subtype = AccountSubtype.create! valid_attributes
      get :show, :id => account_subtype.id.to_s
      assigns(:account_subtype).should eq(account_subtype)
    end
  end

  describe "GET new" do
    it "assigns a new account_subtype as @account_subtype" do
      get :new
      assigns(:account_subtype).should be_a_new(AccountSubtype)
    end
  end

  describe "GET edit" do
    it "assigns the requested account_subtype as @account_subtype" do
      account_subtype = AccountSubtype.create! valid_attributes
      get :edit, :id => account_subtype.id.to_s
      assigns(:account_subtype).should eq(account_subtype)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AccountSubtype" do
        expect {
          post :create, :account_subtype => valid_attributes
        }.to change(AccountSubtype, :count).by(1)
      end

      it "assigns a newly created account_subtype as @account_subtype" do
        post :create, :account_subtype => valid_attributes
        assigns(:account_subtype).should be_a(AccountSubtype)
        assigns(:account_subtype).should be_persisted
      end

      it "redirects to the created account_subtype" do
        post :create, :account_subtype => valid_attributes
        response.should redirect_to(AccountSubtype.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved account_subtype as @account_subtype" do
        # Trigger the behavior that occurs when invalid params are submitted
        AccountSubtype.any_instance.stub(:save).and_return(false)
        post :create, :account_subtype => {}
        assigns(:account_subtype).should be_a_new(AccountSubtype)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AccountSubtype.any_instance.stub(:save).and_return(false)
        post :create, :account_subtype => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested account_subtype" do
        account_subtype = AccountSubtype.create! valid_attributes
        # Assuming there are no other account_subtypes in the database, this
        # specifies that the AccountSubtype created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AccountSubtype.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => account_subtype.id, :account_subtype => {'these' => 'params'}
      end

      it "assigns the requested account_subtype as @account_subtype" do
        account_subtype = AccountSubtype.create! valid_attributes
        put :update, :id => account_subtype.id, :account_subtype => valid_attributes
        assigns(:account_subtype).should eq(account_subtype)
      end

      it "redirects to the account_subtype" do
        account_subtype = AccountSubtype.create! valid_attributes
        put :update, :id => account_subtype.id, :account_subtype => valid_attributes
        response.should redirect_to(account_subtype)
      end
    end

    describe "with invalid params" do
      it "assigns the account_subtype as @account_subtype" do
        account_subtype = AccountSubtype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AccountSubtype.any_instance.stub(:save).and_return(false)
        put :update, :id => account_subtype.id.to_s, :account_subtype => {}
        assigns(:account_subtype).should eq(account_subtype)
      end

      it "re-renders the 'edit' template" do
        account_subtype = AccountSubtype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AccountSubtype.any_instance.stub(:save).and_return(false)
        put :update, :id => account_subtype.id.to_s, :account_subtype => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested account_subtype" do
      account_subtype = AccountSubtype.create! valid_attributes
      expect {
        delete :destroy, :id => account_subtype.id.to_s
      }.to change(AccountSubtype, :count).by(-1)
    end

    it "redirects to the account_subtypes list" do
      account_subtype = AccountSubtype.create! valid_attributes
      delete :destroy, :id => account_subtype.id.to_s
      response.should redirect_to(account_subtypes_url)
    end
  end

end
