require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AccountProductsController do

  # This should return the minimal set of attributes required to create a valid
  # AccountProduct. As you add validations to AccountProduct, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all account_products as @account_products" do
      account_product = AccountProduct.create! valid_attributes
      get :index
      assigns(:account_products).should eq([account_product])
    end
  end

  describe "GET show" do
    it "assigns the requested account_product as @account_product" do
      account_product = AccountProduct.create! valid_attributes
      get :show, :id => account_product.id.to_s
      assigns(:account_product).should eq(account_product)
    end
  end

  describe "GET new" do
    it "assigns a new account_product as @account_product" do
      get :new
      assigns(:account_product).should be_a_new(AccountProduct)
    end
  end

  describe "GET edit" do
    it "assigns the requested account_product as @account_product" do
      account_product = AccountProduct.create! valid_attributes
      get :edit, :id => account_product.id.to_s
      assigns(:account_product).should eq(account_product)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AccountProduct" do
        expect {
          post :create, :account_product => valid_attributes
        }.to change(AccountProduct, :count).by(1)
      end

      it "assigns a newly created account_product as @account_product" do
        post :create, :account_product => valid_attributes
        assigns(:account_product).should be_a(AccountProduct)
        assigns(:account_product).should be_persisted
      end

      it "redirects to the created account_product" do
        post :create, :account_product => valid_attributes
        response.should redirect_to(AccountProduct.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved account_product as @account_product" do
        # Trigger the behavior that occurs when invalid params are submitted
        AccountProduct.any_instance.stub(:save).and_return(false)
        post :create, :account_product => {}
        assigns(:account_product).should be_a_new(AccountProduct)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AccountProduct.any_instance.stub(:save).and_return(false)
        post :create, :account_product => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested account_product" do
        account_product = AccountProduct.create! valid_attributes
        # Assuming there are no other account_products in the database, this
        # specifies that the AccountProduct created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AccountProduct.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => account_product.id, :account_product => {'these' => 'params'}
      end

      it "assigns the requested account_product as @account_product" do
        account_product = AccountProduct.create! valid_attributes
        put :update, :id => account_product.id, :account_product => valid_attributes
        assigns(:account_product).should eq(account_product)
      end

      it "redirects to the account_product" do
        account_product = AccountProduct.create! valid_attributes
        put :update, :id => account_product.id, :account_product => valid_attributes
        response.should redirect_to(account_product)
      end
    end

    describe "with invalid params" do
      it "assigns the account_product as @account_product" do
        account_product = AccountProduct.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AccountProduct.any_instance.stub(:save).and_return(false)
        put :update, :id => account_product.id.to_s, :account_product => {}
        assigns(:account_product).should eq(account_product)
      end

      it "re-renders the 'edit' template" do
        account_product = AccountProduct.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AccountProduct.any_instance.stub(:save).and_return(false)
        put :update, :id => account_product.id.to_s, :account_product => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested account_product" do
      account_product = AccountProduct.create! valid_attributes
      expect {
        delete :destroy, :id => account_product.id.to_s
      }.to change(AccountProduct, :count).by(-1)
    end

    it "redirects to the account_products list" do
      account_product = AccountProduct.create! valid_attributes
      delete :destroy, :id => account_product.id.to_s
      response.should redirect_to(account_products_url)
    end
  end

end
